"use client";

import jsPDF from "jspdf";

export async function exportToPDF(opts: {
  title: string;
  content: string;
  projectName: string;
}) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;

  // header
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageWidth, 25, "F");
  doc.setTextColor(255);
  doc.setFontSize(18);
  doc.text("Oji Brain", margin, 16);
  doc.setFontSize(10);
  doc.text(opts.projectName, pageWidth - margin, 16, { align: "right" });

  // title
  doc.setTextColor(20);
  doc.setFontSize(16);
  doc.text(opts.title, margin, 40);
  doc.setDrawColor(200);
  doc.line(margin, 44, pageWidth - margin, 44);

  // content
  doc.setFontSize(11);
  doc.setTextColor(40);
  const lines = doc.splitTextToSize(opts.content, contentWidth);
  let y = 52;
  for (const line of lines) {
    if (y > pageHeight - 20) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin, y);
    y += 6;
  }

  // footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      `${i} / ${pageCount}  •  Generated by Oji Brain  •  ${new Date().toLocaleDateString("en-GB")}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );
  }

  doc.save(`${opts.title}.pdf`);
}
